version: '3'
services:
  mpt_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - ./mpt_app:/app/mpt_app
  mpt-ui:
    build: 
      context: ./mpt-ui
      dockerfile: ../Dockerfile.ui
    ports:
      - "3000:3000"
    volumes:
      - ./mpt-ui:/app
    depends_on:
      - mpt_app
  